local data = require('main.data')

local world = data.path_world1
local world2 = data.path_world2
local world3 = data.path_world3

local costs = {
    [0] = {
        1.0,  -- E
        1.0,  -- N
        1.0,  -- W
        1.0,  -- S
        1.41, -- NE
        1.41, -- NW
        1.41, -- SW
        1.41  -- SE
    }
}

local map_width = 5
local map_height = 5
local direction = astar.DIRECTION_EIGHT
local allocate = map_width * map_height
local typical_adjacent = 8
local cache = true

local start_x = 0
local start_y = 0

local end_x = 3
local end_y = 3

local function result(path_result, size, total_cost, path)
    print("size:", size)
    print("total_cost:", total_cost)

    if path_result == astar.SOLVED then
        print("SOLVED")
        for i, v in ipairs(path) do
            print("Tile: ", v.x .. "-" .. v.y)
        end
    elseif path_result == astar.NO_SOLUTION then
        print("NO_SOLUTION")
    elseif path_result == astar.START_END_SAME then
        print("START_END_SAME")
    end
end

function init(self)
    -- ***************************** --
    -- * Initial reset empty cache * --
    -- ***************************** --

    astar.reset_cache()

    astar.setup(map_width, map_height, direction, allocate, typical_adjacent, cache)
    astar.set_map(world)
    astar.set_costs(costs)

    local path_result, size, total_cost, path = astar.solve(start_x, start_y, end_x, end_y)
    result(path_result, size, total_cost, path)

    -- ***************************** --
    -- *        Reset cache        * --
    -- ***************************** --
    print("--------------------------")

    astar.reset_cache()

    -- Same w-h. No need to astar.setup.
    -- It is closed. Should return NO_SOLUTION
    astar.set_map(world2)

    local path_result, size, total_cost, path = astar.solve(start_x, start_y, end_x, end_y)
    result(path_result, size, total_cost, path)

    -- ***************************** --
    -- *         Hard Reset        * --
    -- ***************************** --
    print("--------------------------")

    astar.reset()

    map_width = 6
    map_height = 6
    allocate = map_width * map_height
    astar.setup(map_width, map_height, direction, allocate, typical_adjacent, cache)

    -- Since reset() delete the costs array, returns error. This is expected. You have to astar.set_costs(costs) after reset()
    -- Word/Map is filled with 0 on setup()
    local path_result, size, total_cost, path = astar.solve(5, 5, end_x, end_y)
    result(path_result, size, total_cost, path)


    -- ***************************** --
    -- *        Reset cache        * --
    -- ***************************** --
    print("--------------------------")

    astar.reset()

    astar.setup(map_width, map_height, direction, allocate, typical_adjacent, cache)
    astar.set_map(world3)
    astar.set_costs(costs)
    local path_result, size, total_cost, path = astar.solve(5, 5, end_x, end_y)
    result(path_result, size, total_cost, path)
end
